### This tool hasn't actually been worked on yet, these comments are just outlines for me

## IMPORTS HERE

## VARIABLES HERE
# DEFAULT_URL = https://gmt.gvnx.xyz/LRP
# DEFAULT_DELAY = 5
# DEFAULT_AMOUNT = INFINITE
# DEFAULT_VISIBLE = N 

## PROMPTS HERE
# URL = PROMPT WHERE TO GO, IF NO ANSWER THEN USE DEFAULT_URL
# DELAY = PROMPT DELAY BETWEEN NEW TAB, IF NO ANSWER USE DEFAULT_DELAY
# AMOUNT = PROMPT TOTAL AMOUNT OF TABS, IF NO ANSWER USE DEFAULT_AMOUNT
# VIsIBLE = PROMPT IF USER WANTS TO SEE THE TAB (Y/N), IF NO ANSWER USE DEFAULT_VISIBLE

## WHAT PROXY
# LIST OF PROXYS HERE
# PROMPT USER WHICH PROXY TO USE

## OPENING TABS
# ALL THAT STUFF HERE


